plugins: -jest
env:
  node: true
extends: -'airbnb-base'
  -'plugin:jest/recommended'
overrides: []
parserOptions:
  ecmaVersion: latest
rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
